# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: "VectSharp: a light library for C# vector graphics"
email: giorgio.bianchini@bristol.ac.uk
description: >- # this means to ignore newlines until "baseurl:"
  VectSharp is a library to create vector graphics (including text) in C#, without too many dependencies.
  VectSharp is written using .NET Core, and is available for Mac, Windows and Linux under an LGPLv3 license.
baseurl: "/VectSharp" # the subpath of your site, e.g. /blog
url: "https://giorgiobianchini.com" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  arklumpus
favicon: /assets/images/favicon.ico
touch_icon: /assets/images/appletouch.png

# Build settings
markdown: kramdown
remote_theme: pmarsceill/just-the-docs@v0.3.3
color_scheme: VectSharp
logo: "/assets/images/VectSharp.svg"
plugins:
   - jekyll-seo-tag

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
   - Gemfile
   - Gemfile.lock
   - node_modules
   - vendor/bundle/
   - vendor/cache/
   - vendor/gems/
   - vendor/ruby/
   - Blazor/css/open-iconic/README.md
   
compress_html:
  ignore:
    envs: all

include:
    - "_framework"
    - "_bin"
    - "_content"
    
